# Generated by Django 5.2.14 on 2026-05-27 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier using UUID4 to prevent enumeration', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business name of the merchant', max_length=255)),
                ('api_key', models.CharField(help_text='Merchant-specific API key for webhooks', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', help_text='Operational status of the merchant account', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Immutable creation timestamp for audit')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated on model change')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key'], name='merchants_m_api_key_bdb509_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique transaction identifier', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in smallest currency unit', max_digits=15)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current transaction lifecycle status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Immutable transaction creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification time')),
                ('merchant', models.ForeignKey(help_text='Parent merchant this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', '-created_at'], name='merchants_t_merchan_4315f9_idx'), models.Index(fields=['merchant'], name='merchants_t_merchan_d5f862_idx')],
            },
        ),
    ]
